### ISSUE TITLE
Typo in package.json > main

### ISSUE THREAD

**Issue by hilkeheremans** [elgerlambert/redux-localstorage-filter#1]
Packager can't find the module due to a typo in package.json:
`"main": "/lib/filter.js",`
should be
`"main": "lib/filter.js",`

Figured this tiny change was not worth a PR. ;-)

Thanks for the good work!

**Comment by elgerlambert** [comment]
My bad, thanks for letting me know @hilkeheremans!

Fixed by 0355a74 and published to npm as `0.1.1`.
